import Head from 'next/head';

import HomePanes from './HomePanes';

export default function Home() {
	return (
		<>
			<Head>
				<title>Myria</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/logo.ico" />
			</Head>
			<HomePanes />
		</>
	);
}
